### ISSUE TITLE
Maildrop URL needs to be updated

### ISSUE THREAD

**Issue by Eyes0ftheworld** [vitorgalvao/temporary-email-workflow#1]
### Workflow version

2022.1

### Alfred version

5.0.6

### macOS version

Ventura 13.1

### Debugger output

```alfred_debugger
N/A
```

### More details

The Maildrop URL needs to have `?mailbox=` before the `email_name`.
It currently launches an invalid URL if Maildrop is set in the preferences/config.
Ex: `https://maildrop.cc/inbox/?mailbox=a51643a1691a4106l93f85e030b7a7cd`

**Comment by Eyes0ftheworld** [comment]
Updating `info.plist` to the below fixed it for me:

> if [[ "${email_service}" == 'maildrop.cc' ]]; then
> 	readonly url="https://${email_service}/inbox/?mailbox=${email_name}"
> else
> 	readonly url="https://${email_service}/inbox/${email_name}"
> fi

**Comment by vitorgalvao** [comment]
That’s the fix I went with. It’s now available to update from inside the Alfred Preferences.

Thank you for the report.
